### ISSUE TITLE
comfy-ui 无法加载模型

### ISSUE THREAD

**Issue by shadowwider** [IDEA-CCNL/Fooocus-Taiyi-XL#2]
请问是只能用Fooocus吗?用sdwebui还有comfyui均在加载模型时报错。类似这样。
`size mismatch for cond_stage_model.clip_l.transformer.text_model.embeddings.token_embedding.weight: copying a param with shape torch.Size([57475, 768]) from checkpoint, the shape in current model is torch.Size([49408, 768]).`

**Comment by wxj630** [comment]
其他绘图软件也是参考Fooocus去适配就行了，其实主要就是关注（1）正确加载模型：CLIP text encoder的模型词表和位置编码需要扩充；（2）正确加载tokenizer: tokenizer使用Taiyi的这个tokenizer

**Comment by Layer-norm** [comment]
我试着在comfyui上实现了一下，不过模型在comfyui上好像有点色盲，而且中文提示词的表现没有英文提示词效果好。
![taiyi](https://github.com/IDEA-CCNL/Fooocus-Taiyi-XL/assets/140777998/a06b1a16-5ce2-4020-a661-793690904785)

**Comment by Layer-norm** [comment]
![taiyixl](https://github.com/IDEA-CCNL/Fooocus-Taiyi-XL/assets/140777998/870befa7-49b7-4b64-9a08-63eb7a678479)
新春快乐，我的朋友们。
https://github.com/Layer-norm/ComfyUI-Taiyi
