### ISSUE TITLE
部署代码无法运行或运行后UI无反应 ：huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/cognitive_comp/wuxiaojun/pretrained/pytorch/taiyi-diffusion-xl-base-1.0-text_encoder_pretrained/tokenizer'

### ISSUE THREAD

**Issue by zxy2020** [IDEA-CCNL/Fooocus-Taiyi-XL#3]
无法自主下载：/taiyi-diffusion-xl-base-1.0-text_encoder_pretrained/tokenizer'。。
替代为本地路 ./Fooocus-Taiyi-XL-main/backend/headless/fcbh/sd1_tokenizer 不报错，

![image](https://github.com/IDEA-CCNL/Fooocus-Taiyi-XL/assets/59002646/c28f275a-ef48-43e5-abaf-ffd37cbb52c5)

但是UI点击没反应

![image](https://github.com/IDEA-CCNL/Fooocus-Taiyi-XL/assets/59002646/9ebbbd8e-9096-4eea-a720-925821b5bb8b)

**Comment by wxj630** [comment]
第一个：把tokenizer换成huggingface下载下来的模型里面的tokenizer/目录：https://huggingface.co/IDEA-CCNL/Taiyi-Stable-Diffusion-XL-3.5B
第二个：升级到最新gradio

**Comment by zxy2020** [comment]
> 第一个：把tokenizer换成huggingface下载下来的模型里面的tokenizer/目录：https://huggingface.co/IDEA-CCNL/Taiyi-Stable-Diffusion-XL-3.5B 第二个：升级到最新gradio

您好，感谢你的回复。。通过升级gradio后能正常运行了。。
但是运行论文测试文字，“宇航员骑着白马”，出不来，采样很多次。英文可以，请问可能是我配置tokenizer的问题吗？如何论文中一些图片的详细参数
![image](https://github.com/IDEA-CCNL/Fooocus-Taiyi-XL/assets/59002646/2562219d-02e8-4c15-8fd6-37a2005647b5)

an astronaut riding a white horse
![image](https://github.com/IDEA-CCNL/Fooocus-Taiyi-XL/assets/59002646/68ce5c95-dc57-4888-aebf-c4715faf41a7)

**Comment by wxj630** [comment]
试试加权重“宇航员骑着(白马:1.5)”。

你应该可以注意到程序后台会打出tokenize之后的token_id和权重，你可以拿出来用taiyi tokenizer再decode回自然语言，核对下tokenizer是否正确加载了，照理说是没啥问题的

**Comment by ApolloRay** [comment]
> > 第一个：把tokenizer换成huggingface下载下来的模型里面的tokenizer/目录：https://huggingface.co/IDEA-CCNL/Taiyi-Stable-Diffusion-XL-3.5B 第二个：升级到最新gradio
> 
> 您好，感谢你的回复。。通过升级gradio后能正常运行了。。 但是运行论文测试文字，“宇航员骑着白马”，出不来，采样很多次。英文可以，请问可能是我配置tokenizer的问题吗？如何论文中一些图片的详细参数 ![image](https://private-user-images.githubusercontent.com/59002646/301377458-2562219d-02e8-4c15-8fd6-37a2005647b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3Njc1NTUsIm5iZiI6MTcwNjc2NzI1NSwicGF0aCI6Ii81OTAwMjY0Ni8zMDEzNzc0NTgtMjU2MjIxOWQtMDJlOC00YzE1LThmZDYtMzdhMjAwNTY0N2I1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDA2MDA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhNzFkZTE3MTYxMDJiNjZjOTY4MjdiODgwODIzMTQ1YmI4ODc2NGU2NTI5ZTI1OTgwYTk0YjFlNTc5OWI3MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._zLq84_GUt_R5q8BLYeIgDMd8l1J5ewWBmiRHW8D0KU)
> 
> an astronaut riding a white horse ![image](https://private-user-images.githubusercontent.com/59002646/301377968-68ce5c95-dc57-4888-aebf-c4715faf41a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3Njc1NTUsIm5iZiI6MTcwNjc2NzI1NSwicGF0aCI6Ii81OTAwMjY0Ni8zMDEzNzc5NjgtNjhjZTVjOTUtZGM1Ny00ODg4LWFlYmYtYzQ3MTVmYWY0MWE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDA2MDA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlOGRmZGMyMmI0MDI4NGNiOGE1MGRmOTQ4MjY3NjljODg5NDUyZGZiMzlkNDM5N2U3NDAwNzhmNDIzMjNhMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KTL-Bf2ec9zDMl4QucpGXT5A2YOfrqrhpoef8SNKAO8)

请问升级到最新的gradio==4.16.0的话，不会报IOComponent的问题吗？gradio.component.base里已经没有IOComponent了。

**Comment by ApolloRay** [comment]
> 第一个：把tokenizer换成huggingface下载下来的模型里面的tokenizer/目录：https://huggingface.co/IDEA-CCNL/Taiyi-Stable-Diffusion-XL-3.5B 第二个：升级到最新gradio

升级到最新gradio后，在gradio_hijack下有多个不匹配的模块，无法正常打开页面。
