### ISSUE TITLE
ModuleNotFoundError: No module named 'fengshen'怎么解决

### ISSUE THREAD

**Issue by Lily920** [IDEA-CCNL/Fooocus-Taiyi-XL#7]
You
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[6], line 11
      4 from pytorch_lightning import (
      5     LightningModule,
      6     Trainer,
      7 )
      8 from pytorch_lightning.callbacks import (
      9     LearningRateMonitor,
     10 )
---> 11 from fengshen.data.universal_datamodule import UniversalDataModule
     12 from fengshen.models.model_utils import (
     13     add_module_args,
     14     configure_optimizers,
     15     get_total_steps,
     16 )
     17 from fengshen.utils.universal_checkpoint import UniversalCheckpoint

ModuleNotFoundError: No module named 'fengshen'
出现这个问题怎么解决呢

**Comment by wxj630** [comment]
not about this repo
